version: '2.1'
services:

  uploader:
    build: .
    environment:
      FLASK_DEBUG: 1
      APP_SETTINGS: "config.Development"
      S3_BUCKET: "development"
      S3_KEY: "anAWSkey"
      S3_SECRET: "anAWSsecret"
    volumes:
      - ./src/:/app/
    ports:
      - 5000:5000
    depends_on:
      - localstack

  localstack:
    image: localstack/localstack
    ports:
      - "4572:4572"
    environment:
      - SERVICES=s3
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
